### PR TITLE
Find containers from data attribute

### PR DESCRIPTION
**Pull request by daun**
- Add new way of finding morphable containers: `data-swup-morph` attribute with unique value
- Useful for dynamically generated containers

### CODE REVIEW

**Review by hirasso — COMMENTED** [review]
Very nice! I'm unsure if the console warning should also be thrown for dynamic containers added via data attributes. What's your opinion on that?

You could suppress the warning if `options.containers` is empty

**Comment by hirasso** [comment]
Oops already merged 😁

**Comment by daun** [comment]
In my mind, dynamic containers have slightly different constraints and expectations. Let me think on it. Never too late for a fix release 🤠

**Comment by daun** [comment]
What's a situation where you'd appreciate a warning, where it would help to debug?

**Comment by hirasso** [comment]
When I globally define `options.containers`. Alternatively, setting `options.debug` to `false` would also work for me.

**Comment by daun** [comment]
There's no debug option in this plugin 🫣

Somehow thinking through this makes my head hurt, I'll open an issue so we can keep track of it.

**Comment by hirasso** [comment]
I know there's no debug option yet :) ...lets talk it through together sometime soon. No rush.

**Pull request merged**
